# Generated by Django 4.1 on 2025-07-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('action_flag', models.CharField(max_length=200)),
                ('app', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Userlog',
                'verbose_name_plural': 'Userlogs',
                'db_table': 'userlogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['id'], name='userlogs_id_41a167_idx'),
        ),
    ]
