# Generated by Django 4.1 on 2025-07-01 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niy', models.IntegerField(default=0, verbose_name='NIY')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='Nama Pembina')),
                ('gender', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='L', max_length=1)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, default='smaitalbinaa.ekskul@outlook.com', max_length=254)),
                ('phone', models.CharField(blank=True, default=0, max_length=20)),
                ('photo', models.ImageField(blank=True, default='blank-profile.png', help_text='format foto .jpg/.jpeg', null=True, upload_to=users.models.PathAndRename('user'))),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'ordering': ['teacher_name'],
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['id', 'niy'], name='teachers_id_a1a279_idx'),
        ),
    ]
