# Generated by Django 5.2.3 on 2025-07-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(blank=True, default='Aktif', help_text='Status aktif atau tidaknya guru ini', max_length=20, null=True),
        ),
    ]
