# Generated by Django 5.2.3 on 2025-07-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='short_name',
            field=models.CharField(blank=True, help_text='Nama singkat pembina, misal: Aam Hamdani, S.Pd. menjadi Aam', max_length=100, null=True, verbose_name='Nama Singkat'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, help_text='Alamat lengkap pembina, misal: Jl. Raya No. 123, Jakarta', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='job',
            field=models.CharField(blank=True, help_text='Pekerjaan pembina, misal: Guru Matematika, Kepala Sekolah, dll', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, default=0, help_text='Nomor telepon pembina, misal: 08123456789', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(help_text='Nama lengkap pembina, misal: Aam Hamdani, S.Pd.', max_length=100, verbose_name='Nama Pembina'),
        ),
    ]
