# Generated by Django 5.2.3 on 2025-07-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacher_short_name_alter_teacher_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='day_off',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], default='Sabtu', help_text="The teacher's designated day off.", max_length=10),
        ),
    ]
