# Generated by Django 5.2.3 on 2025-07-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacher_day_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='work_area',
            field=models.CharField(blank=True, help_text='Wilayah Kerja guru ini', max_length=20, null=True),
        ),
    ]
