# Generated by Django 5.2.3 on 2025-07-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Judul Galeri')),
                ('image', models.FileField(help_text='Format .jpg/.png', upload_to='gallery/activity', verbose_name='Gambar')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption Gambar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'db_table': 'galleries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id'], name='galleries_id_85f3c0_idx')],
            },
        ),
    ]
