# Generated by Django 5.2.3 on 2025-07-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_class__class_name', 'student_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
