# Generated by Django 5.2.3 on 2026-04-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='semester',
            field=models.CharField(default='Genap', max_length=7, null=True),
        ),
    ]
