# Generated by Django 5.2.3 on 2025-07-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_dailyplan_academic_year_dailyplan_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='academic_year',
            field=models.CharField(blank=True, default='2025/2026', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='semester',
            field=models.CharField(default='Ganjil', max_length=7, null=True),
        ),
    ]
