# Generated by Django 4.1 on 2025-07-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True, verbose_name='Nama Kelas')),
                ('short_class_name', models.CharField(max_length=20, verbose_name='Nama Singkat Kelas')),
                ('category', models.CharField(choices=[(None, '----Pilih Kategori Kelas----'), ('Putra', 'Putra'), ('Putri', 'Putri')], default='Putra', max_length=20, verbose_name='Kode Pelajaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
                'ordering': ['class_name'],
            },
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['id', 'class_name'], name='classes_id_0814f7_idx'),
        ),
    ]
