# Generated by Django 5.2.3 on 2025-07-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='Nama Event')),
                ('event_date', models.DateField(verbose_name='Tanggal Event')),
                ('event_notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Deskripsi')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori')),
                ('type', models.CharField(choices=[('putra', 'Putra'), ('putri', 'Putri')], default='putra', max_length=20, verbose_name='Tipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Calendar',
                'verbose_name_plural': 'Academic Calendars',
                'db_table': 'academic_calendar',
                'ordering': ['event_name'],
                'indexes': [models.Index(fields=['id', 'event_name', 'event_date'], name='academic_ca_id_4d43a0_idx')],
            },
        ),
    ]
