# Generated by Django 5.2.3 on 2025-08-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='event_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Berakhir Event'),
        ),
    ]
