# Generated by Django 4.1 on 2025-07-01 14:04

from django.db import migrations, models
import django.db.models.deletion
import laporan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('extracurriculars', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Report Date')),
                ('report_notes', models.TextField(blank=True, max_length=200, verbose_name='Notes')),
                ('photo', models.ImageField(default='no-image.png', help_text='Image must be .jpg/.jpeg/.png format', upload_to=laporan.models.PathAndRename('ekskul/laporan'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extracurriculars.extracurricular')),
                ('students', models.ManyToManyField(help_text='Ketik nama yang ingin dicari dan pilih. Kamu bisa memilih lebih dari 1 (satu). Untuk menghapusnya, klik nama yang ingin dihapus hingga berwarna biru/terang, lalu tekan delete atau backspace.', to='students.student')),
                ('teacher', models.ManyToManyField(help_text='Ketik nama yang ingin dicari dan pilih. Kamu bisa memilih lebih dari 1 (satu). Untuk menghapusnya, klik nama yang ingin dihapus hingga berwarna biru/terang, lalu tekan delete atau backspace.', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'extracurricular_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['id', 'report_date'], name='extracurric_id_810794_idx'),
        ),
    ]
