# Generated by Django 5.2.3 on 2025-08-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(db_index=True, help_text='Pada PC, Tekan Ctrl untuk memilih lebih dari satu kategori', related_name='posts', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Jika tidak diisi, akan otomatis terisi dengan judul', max_length=255, unique_for_date='created_at'),
        ),
    ]
