# Generated by Django 4.1 on 2025-07-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('extracurriculars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=3)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracurricular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='extracurriculars.extracurricular')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'db_table': 'scores',
                'ordering': ['student', 'extracurricular'],
            },
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['id'], name='scores_id_ab828f_idx'),
        ),
    ]
