# Generated by Django 4.1 on 2025-07-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tahfidz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pembimbing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pembimbing')),
                ('hafalan', models.CharField(max_length=255, verbose_name='Juz yang dihafal')),
                ('pencapaian_sebelumnya', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pencapaian Sebelumnya')),
                ('pencapaian_sekarang', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pencapaian Sekarang')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Santri')),
            ],
            options={
                'verbose_name': 'Tahfidz',
                'verbose_name_plural': 'Tahfidz',
                'db_table': 'tahfidz',
                'ordering': ['-santri'],
            },
        ),
        migrations.AddIndex(
            model_name='tahfidz',
            index=models.Index(fields=['id'], name='tahfidz_id_f6bad8_idx'),
        ),
    ]
