# Generated by Django 5.2.3 on 2025-07-30 08:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tahfidz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pembimbing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pembimbing')),
                ('hafalan', models.CharField(max_length=255, verbose_name='Juz yang dihafal')),
                ('pencapaian_sebelumnya', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pencapaian Sebelumnya')),
                ('pencapaian_sekarang', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pencapaian Sekarang')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catatan')),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Santri')),
            ],
            options={
                'verbose_name': 'Tahfidz',
                'verbose_name_plural': 'Tahfidz',
                'db_table': 'tahfidz',
                'ordering': ['-santri'],
                'indexes': [models.Index(fields=['id'], name='tahfidz_id_f6bad8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tilawah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.now, verbose_name='Tanggal')),
                ('tercapai', models.BooleanField(blank=True, choices=[(True, 'True'), (False, 'False')], default=True, max_length=10, null=True, verbose_name='Tercapai?')),
                ('target', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Target Tilawah Hari Ini')),
                ('halaman', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Halaman')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catatan')),
                ('tajwid', models.CharField(blank=True, choices=[(None, '----Pilih Nilai Tahsin Tajwid----'), ('Mumtaz', 'Mumtaz'), ('Jayyid Jiddan', 'Jayyid Jiddan'), ('Jayyid', 'Jayyid'), ('Maqbul', 'Maqbul'), ("Da'if", "Da'if")], max_length=255, null=True, verbose_name='Tajwid')),
                ('kelancaran', models.CharField(blank=True, choices=[(None, '----Pilih Nilai Tahsin Tajwid----'), ('Mumtaz', 'Mumtaz'), ('Jayyid Jiddan', 'Jayyid Jiddan'), ('Jayyid', 'Jayyid'), ('Maqbul', 'Maqbul'), ("Da'if", "Da'if")], max_length=255, null=True, verbose_name='Kelancaran')),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pendamping', models.ManyToManyField(blank=True, max_length=255, related_name='Pendamping', to='users.teacher')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Santri')),
            ],
            options={
                'verbose_name': 'Tilawah',
                'verbose_name_plural': 'Tilawah',
                'db_table': 'tilawah',
                'ordering': ['-tanggal', 'santri'],
                'indexes': [models.Index(fields=['id'], name='tilawah_id_ea79ec_idx')],
            },
        ),
    ]
