# Generated by Django 5.2.3 on 2025-08-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('tahfidz', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tilawah',
            unique_together={('tanggal', 'santri'), ('tanggal', 'santri', 'semester', 'academic_year')},
        ),
    ]
