# Generated by Django 5.2.3 on 2025-08-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0002_alter_tilawah_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilawah',
            name='kehadiran',
            field=models.CharField(blank=True, choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Alpa', 'Alpa')], default='Hadir', max_length=10, null=True, verbose_name='Kehadiran'),
        ),
    ]
