# Generated by Django 5.2.3 on 2025-07-27 01:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_face_encoding'),
        ('tahfidz', '0003_alter_tahfidz_academic_year_alter_tahfidz_semester'),
        ('users', '0004_teacher_day_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tilawah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.now, verbose_name='Tanggal')),
                ('halaman', models.CharField(blank=True, max_length=255, null=True, verbose_name='Halaman')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catatan')),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pendamping', models.ManyToManyField(blank=True, max_length=255, null=True, related_name='Pendamping', to='users.teacher')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Santri')),
            ],
            options={
                'verbose_name': 'Tilawah',
                'verbose_name_plural': 'Tilawah',
                'db_table': 'tilawah',
                'ordering': ['-tanggal', 'santri'],
                'indexes': [models.Index(fields=['id'], name='tilawah_id_ea79ec_idx')],
            },
        ),
    ]
