# Generated by Django 5.2.3 on 2025-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0003_tilawah_kehadiran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilawah',
            name='kehadiran',
            field=models.CharField(blank=True, choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Telat', 'Telat'), ('Izin', 'Izin'), ('Alpa', 'Alpa')], default='Hadir', max_length=10, null=True, verbose_name='Kehadiran'),
        ),
        migrations.AlterField(
            model_name='tilawah',
            name='kelancaran',
            field=models.CharField(blank=True, choices=[(None, '----Pilih Nilai Tahsin----'), ('Mumtaz', 'Mumtaz'), ('Jayyid Jiddan', 'Jayyid Jiddan'), ('Jayyid', 'Jayyid'), ('Maqbul', 'Maqbul'), ("Da'if", "Da'if")], max_length=255, null=True, verbose_name='Kelancaran'),
        ),
        migrations.AlterField(
            model_name='tilawah',
            name='tajwid',
            field=models.CharField(blank=True, choices=[(None, '----Pilih Nilai Tahsin----'), ('Mumtaz', 'Mumtaz'), ('Jayyid Jiddan', 'Jayyid Jiddan'), ('Jayyid', 'Jayyid'), ('Maqbul', 'Maqbul'), ("Da'if", "Da'if")], max_length=255, null=True, verbose_name='Tajwid'),
        ),
    ]
