# Generated by Django 5.2.3 on 2025-07-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0004_tilawah'),
        ('users', '0004_teacher_day_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilawah',
            name='pendamping',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='Pendamping', to='users.teacher'),
        ),
    ]
