# Generated by Django 5.2.3 on 2025-07-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0005_alter_tilawah_pendamping'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilawah',
            name='tercapai',
            field=models.BooleanField(blank=True, choices=[(True, 'True'), (False, 'False')], default=True, max_length=10, null=True, verbose_name='Tercapai?'),
        ),
    ]
