# Generated by Django 5.2.3 on 2025-08-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0005_tilawah_ayat_tilawah_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilawah',
            name='academic_year',
            field=models.CharField(default='2025/2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='tilawah',
            name='semester',
            field=models.CharField(default='Ganjil', max_length=7),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('nomor_surat', models.CharField(max_length=255, verbose_name='No Surat')),
                ('nama_surat', models.CharField(max_length=255, verbose_name='Nama Surat')),
                ('ayat', models.CharField(max_length=255, verbose_name='Ayat')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catatan')),
                ('semester', models.CharField(default='Ganjil', max_length=7)),
                ('academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Target',
                'db_table': 'tilawah_target',
                'ordering': ['tanggal'],
                'indexes': [models.Index(fields=['id'], name='tilawah_tar_id_f0168f_idx')],
                'unique_together': {('tanggal', 'nomor_surat', 'ayat'), ('tanggal', 'nomor_surat', 'ayat', 'semester', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='tilawah',
            name='target_tilawah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tahfidz.target', verbose_name='Target'),
        ),
    ]
