# Generated by Django 5.2.3 on 2025-08-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0006_alter_tilawah_academic_year_alter_tilawah_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='ayat',
            field=models.PositiveBigIntegerField(verbose_name='Ayat'),
        ),
        migrations.AlterField(
            model_name='target',
            name='nomor_surat',
            field=models.PositiveBigIntegerField(verbose_name='No Surat'),
        ),
        migrations.AlterField(
            model_name='tilawah',
            name='ayat',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Ayat Terakhir'),
        ),
    ]
