# Generated by Django 5.2.3 on 2025-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0006_tilawah_tercapai'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilawah',
            name='target',
            field=models.PositiveBigIntegerField(blank=True, max_length=255, null=True, verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='tilawah',
            name='halaman',
            field=models.PositiveBigIntegerField(blank=True, max_length=255, null=True, verbose_name='Halaman'),
        ),
    ]
