# Generated by Django 5.2.3 on 2025-07-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0007_tilawah_target_alter_tilawah_halaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilawah',
            name='halaman',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Halaman'),
        ),
        migrations.AlterField(
            model_name='tilawah',
            name='target',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Target'),
        ),
    ]
