# Generated by Django 5.2.3 on 2025-07-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0008_alter_tilawah_halaman_alter_tilawah_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilawah',
            name='target',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Target Tilawah Hari Ini'),
        ),
    ]
