# Generated by Django 5.2.3 on 2026-04-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0009_alter_tilawah_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahfidz',
            name='semester',
            field=models.CharField(default='Genap', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='semester',
            field=models.CharField(default='Genap', max_length=7),
        ),
        migrations.AlterField(
            model_name='tilawah',
            name='semester',
            field=models.CharField(default='Genap', max_length=7),
        ),
    ]
