# Generated by Django 5.2.3 on 2025-07-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0010_tilawah_kelancaran_tilawah_tajwid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilawah',
            name='kelancaran',
            field=models.CharField(blank=True, choices=[(None, '----Pilih Nilai Tahsin Tajwid----'), ('Mumtaz', 'Mumtaz'), ('Jayyid Jiddan', 'Jayyid Jiddan'), ('Jayyid', 'Jayyid'), ('Maqbul', 'Maqbul'), ("Da'if", "Da'if")], max_length=255, null=True, verbose_name='Kelancaran'),
        ),
        migrations.AlterField(
            model_name='tilawah',
            name='tajwid',
            field=models.CharField(blank=True, choices=[(None, '----Pilih Nilai Tahsin Tajwid----'), ('Mumtaz', 'Mumtaz'), ('Jayyid Jiddan', 'Jayyid Jiddan'), ('Jayyid', 'Jayyid'), ('Maqbul', 'Maqbul'), ("Da'if", "Da'if")], max_length=255, null=True, verbose_name='Tajwid'),
        ),
    ]
