# Generated by Django 5.2.3 on 2025-07-30 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Tanggal')),
                ('duty', models.TextField(blank=True, help_text='Opsional. Jika ada', max_length=250, null=True, verbose_name='Tugas')),
                ('notes', models.TextField(blank=True, help_text='Opsional. Jika ada', max_length=250, null=True, verbose_name='Keterangan')),
                ('status', models.CharField(choices=[(None, '----Pilih Status----'), ('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan')], default='Hadir', max_length=20, verbose_name='Status')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Sudah di-submit?')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Sudah complete')),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('type', models.CharField(choices=[(None, '----Pilih Kategori Kelas----'), ('Putra', 'Putra'), ('Putri', 'Putri')], default='Putra', max_length=20, verbose_name='Tipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to='users.teacher', verbose_name='Petugas Piket')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='schedules.schedule', verbose_name='Jadwal')),
                ('subtitute_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtitute_teacher', to='users.teacher', verbose_name='Guru Pengganti')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'class_reports',
                'ordering': ['-report_date', 'schedule__schedule_class', 'schedule__schedule_time'],
                'indexes': [models.Index(fields=['report_date'], name='class_repor_report__704d2e_idx')],
                'unique_together': {('report_date', 'schedule'), ('report_date', 'schedule', 'type', 'semester', 'academic_year')},
            },
        ),
    ]
