# Generated by Django 5.2.3 on 2025-09-07 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('schedules', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonTeacherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Tanggal')),
                ('status', models.CharField(choices=[(None, '----Pilih Status----'), ('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan')], default='Hadir', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Opsional. Jika ada', max_length=250, null=True, verbose_name='Keterangan')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Sudah di-submit?')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Sudah complete')),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('type', models.CharField(choices=[(None, '----Pilih Kategori Kelas----'), ('Putra', 'Putra'), ('Putri', 'Putri')], default='Putra', max_length=20, verbose_name='Tipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonteachers', to='schedules.period', verbose_name='Jam ke-')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonteachers', to='users.teacher', verbose_name='Namas')),
            ],
            options={
                'verbose_name': 'Non Teacher Report',
                'verbose_name_plural': 'Non Teacher Reports',
                'db_table': 'non_teacher_reports',
                'ordering': ['-report_date', 'schedule_time', 'teacher__teacher_name'],
                'indexes': [models.Index(fields=['report_date'], name='non_teacher_report__29982b_idx')],
                'unique_together': {('report_date', 'teacher', 'schedule_time'), ('report_date', 'teacher', 'type', 'semester', 'academic_year')},
            },
        ),
    ]
