# Generated by Django 5.2.3 on 2025-09-08 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_nonteacherreport'),
        ('schedules', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nonteacherreport',
            unique_together={('report_date', 'teacher', 'schedule_time')},
        ),
        migrations.AlterField(
            model_name='nonteacherreport',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonteachers', to='users.teacher', verbose_name='Nama'),
        ),
        migrations.AlterUniqueTogether(
            name='nonteacherreport',
            unique_together={('report_date', 'teacher', 'schedule_time'), ('report_date', 'teacher', 'schedule_time', 'type', 'semester', 'academic_year')},
        ),
    ]
