# Generated by Django 5.2.3 on 2026-04-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_nonteacherreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteacherreport',
            name='semester',
            field=models.CharField(default='Genap', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='nonteacherreport',
            name='status',
            field=models.CharField(choices=[(None, '----Pilih Status----'), ('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan'), ('Off', 'Off')], default='Hadir', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='semester',
            field=models.CharField(default='Genap', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[(None, '----Pilih Status----'), ('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan'), ('Off', 'Off')], default='Hadir', max_length=20, verbose_name='Status'),
        ),
    ]
