# Generated by Django 5.2.3 on 2025-07-04 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_academic_year_alter_report_semester'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to='users.teacher', verbose_name='Petugas Piket'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subtitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtitute_teacher', to='users.teacher', verbose_name='Guru Pengganti'),
        ),
    ]
