# Generated by Django 5.2.3 on 2025-07-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_reporter_alter_report_subtitute_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('putra', 'Putra'), ('putri', 'Putri')], default='putra', max_length=20, verbose_name='Tipe'),
        ),
    ]
