# Generated by Django 5.2.3 on 2025-07-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_type'),
        ('schedules', '0006_schedule_teacher_alter_reporterschedule_schedule_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='schedules.schedule', verbose_name='Jadwal'),
        ),
    ]
