# Generated by Django 5.2.3 on 2025-07-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[(None, '----Pilih Kategori Kelas----'), ('Putra', 'Putra'), ('Putri', 'Putri')], default='Putra', max_length=20, verbose_name='Tipe'),
        ),
    ]
