# Generated by Django 5.2.3 on 2025-07-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_type'),
        ('schedules', '0009_alter_schedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('report_date', 'schedule'), ('report_date', 'schedule', 'type', 'semester', 'academic_year')},
        ),
    ]
