# Generated by Django 4.1 on 2025-07-01 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='Nama Pelajaran')),
                ('course_short_name', models.CharField(default='', max_length=30, verbose_name='Nama Singkat')),
                ('course_code', models.CharField(blank=True, max_length=20, verbose_name='Kode Pelajaran')),
                ('category', models.CharField(choices=[(None, '----Pilih Kategori----'), ("Syar'i", "Syar'i"), ('Ashri', 'Ashri'), ('Netral', 'Netral')], default="Syar'i", max_length=20, verbose_name='Kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Guru')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['course_name'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['id', 'course_name'], name='courses_id_ce70a8_idx'),
        ),
    ]
