# Generated by Django 5.2.3 on 2025-07-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='consecutive_periods_needed',
            field=models.PositiveIntegerField(default=1, help_text='Number of consecutive periods for one session (e.g., 2 for a double period).'),
        ),
        migrations.AddField(
            model_name='course',
            name='periods_per_week',
            field=models.PositiveIntegerField(default=1, help_text='Number of periods this lesson occurs per week (1-4).'),
        ),
    ]
