# Generated by Django 5.2.3 on 2025-07-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0004_course_consecutive_periods_needed_and_more'),
        ('users', '0005_teacher_work_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Pelajaran')),
                ('short_name', models.CharField(default='', max_length=30, verbose_name='Nama Singkat')),
                ('category', models.CharField(choices=[(None, '----Pilih Kategori----'), ("Syar'i", "Syar'i"), ('Ashri', 'Ashri'), ('Netral', 'Netral')], default="Syar'i", max_length=20, verbose_name='Kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Subject',
                'verbose_name_plural': 'Course Subjects',
                'db_table': 'subject',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_id_ce70a8_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_short_name',
        ),
        migrations.AddField(
            model_name='course',
            name='class_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='classes.class', verbose_name='Kelas'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='users.teacher', verbose_name='Guru'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['id', 'name'], name='subject_id_c229ba_idx'),
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.subject', verbose_name='Mata Pelajaran'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['id', 'course'], name='courses_id_07ef52_idx'),
        ),
    ]
