# Generated by Django 5.2.3 on 2025-07-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subject_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.CharField(default='Aktif', max_length=50, verbose_name='Status Pelajaran'),
        ),
    ]
