# Generated by Django 5.2.3 on 2025-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_subject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[(None, '----Pilih Kategori Kelas----'), ('putra', 'Putra'), ('putri', 'Putri')], default='putra', max_length=20, verbose_name='Tipe'),
        ),
    ]
