# Generated by Django 5.2.3 on 2025-07-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[(None, '----Pilih Kategori Kelas----'), ('Putra', 'Putra'), ('Putra', 'Putri'), ('Putra-Putri', 'Putra & Putri')], default='Putra', max_length=20, verbose_name='Tipe'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[(None, '----Pilih Kategori Kelas----'), ('Putra', 'Putra'), ('Putra', 'Putri'), ('Putra-Putri', 'Putra & Putri')], default='Putra', max_length=20, verbose_name='Tipe'),
        ),
    ]
