# Generated by Django 5.2.3 on 2025-07-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestasi',
            name='academic_year',
            field=models.CharField(blank=True, default='2024/2025', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='semester',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='programprestasi',
            name='academic_year',
            field=models.CharField(blank=True, default='2024/2025', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='programprestasi',
            name='semester',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
