# Generated by Django 4.1 on 2025-07-01 14:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_day', models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], max_length=10, verbose_name='Hari')),
                ('schedule_time', models.CharField(choices=[('1', 'Jam ke-1'), ('2', 'Jam ke-2'), ('3', 'Jam ke-3'), ('4', 'Jam ke-4'), ('5', 'Jam ke-5'), ('6', 'Jam ke-6'), ('7', 'Jam ke-7'), ('8', 'Jam ke-8'), ('9', 'Jam ke-9')], max_length=20, verbose_name='Jam Ke-')),
                ('time_start', models.TimeField(default=datetime.time(7, 0), verbose_name='Waktu Mulai')),
                ('time_end', models.TimeField(default=datetime.time(7, 0), verbose_name='Waktu Akhir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class', verbose_name='Kelas')),
                ('schedule_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Pelajaran')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'ordering': ['-schedule_day', 'schedule_class', 'schedule_time'],
            },
        ),
        migrations.CreateModel(
            name='ReporterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_day', models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], max_length=10, verbose_name='Hari')),
                ('schedule_time', models.CharField(choices=[('1', 'Jam ke-1'), ('2', 'Jam ke-2'), ('3', 'Jam ke-3'), ('4', 'Jam ke-4'), ('5', 'Jam ke-5'), ('6', 'Jam ke-6'), ('7', 'Jam ke-7'), ('8', 'Jam ke-8'), ('9', 'Jam ke-9')], max_length=20, verbose_name='Jam Ke-')),
                ('time_start', models.TimeField(default=datetime.time(7, 0), verbose_name='Waktu Mulai')),
                ('time_end', models.TimeField(default=datetime.time(7, 0), verbose_name='Waktu Akhir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tim Piket')),
            ],
            options={
                'verbose_name': 'Reporter Schedule',
                'verbose_name_plural': 'Reporter Schedules',
                'db_table': 'reporter_schedules',
                'ordering': ['-schedule_day', 'schedule_time'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_day', 'schedule_time'], name='schedules_schedul_ff210a_idx'),
        ),
        migrations.AddIndex(
            model_name='reporterschedule',
            index=models.Index(fields=['schedule_day', 'schedule_time'], name='reporter_sc_schedul_449fa5_idx'),
        ),
    ]
