# Generated by Django 5.2.3 on 2026-04-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_reporterschedule_semester_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
