# Generated by Django 5.2.3 on 2025-07-04 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_reporterschedule_academic_year_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporterschedule',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher', verbose_name='Tim Piket'),
        ),
    ]
