# Generated by Django 5.2.3 on 2025-07-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_reporterschedule_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporterschedule',
            name='type',
            field=models.CharField(choices=[('putra', 'Putra'), ('putri', 'Putri')], default='putra', max_length=20, verbose_name='Tipe'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('putra', 'Putra'), ('putri', 'Putri')], default='putra', max_length=20, verbose_name='Tipe'),
        ),
    ]
