# Generated by Django 5.2.3 on 2025-07-26 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('schedules', '0005_reporterschedule_type_schedule_type'),
        ('users', '0004_teacher_day_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='reporterschedule',
            name='schedule_day',
            field=models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], max_length=10, verbose_name='Hari'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_day',
            field=models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], max_length=10, verbose_name='Hari'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('schedule_day', 'schedule_time', 'schedule_class'), ('schedule_day', 'schedule_time', 'teacher')},
        ),
    ]
