# Generated by Django 5.2.3 on 2025-07-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0005_subject_alter_course_options_and_more'),
        ('schedules', '0006_schedule_teacher_alter_reporterschedule_schedule_day_and_more'),
        ('users', '0005_teacher_work_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('time_start', models.TimeField()),
                ('short_time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('short_time_end', models.TimeField()),
                ('type', models.CharField(choices=[('putra', 'Putra'), ('putri', 'Putri')], default='putra', max_length=20, verbose_name='Tipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'db_table': 'periods',
                'ordering': ['number', 'type'],
            },
        ),
        migrations.RenameIndex(
            model_name='schedule',
            new_name='schedules_schedul_6b3f5c_idx',
            old_name='schedules_schedul_ff210a_idx',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_start',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='academic_year',
            field=models.CharField(blank=True, default='2025/2026', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='classes.class', verbose_name='Kelas'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='courses.course', verbose_name='Pelajaran'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.teacher'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['id', 'number'], name='periods_id_caf3d8_idx'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='schedules.period', verbose_name='Jam ke-'),
        ),
    ]
