# Generated by Django 5.2.3 on 2025-07-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='type',
            field=models.CharField(choices=[(None, '----Pilih Kategori Kelas----'), ('Putra', 'Putra'), ('Putri', 'Putri')], default='Putra', max_length=20, verbose_name='Tipe'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[(None, '----Pilih Kategori Kelas----'), ('Putra', 'Putra'), ('Putri', 'Putri')], default='Putra', max_length=20, verbose_name='Tipe'),
        ),
    ]
