# Generated by Django 5.2.3 on 2025-07-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('schedules', '0008_alter_period_type_alter_schedule_type'),
        ('users', '0005_teacher_work_area'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('schedule_day', 'schedule_time', 'teacher')},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='academic_year',
            field=models.CharField(default='2025/2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.CharField(default='Ganjil', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('schedule_day', 'schedule_time', 'schedule_class', 'type', 'semester', 'academic_year'), ('schedule_day', 'schedule_time', 'teacher')},
        ),
    ]
