# Generated by Django 5.2.3 on 2025-07-21 18:46

import django.db.models.deletion
import utils.datetime_wtih_tz
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_student_face_encoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=utils.datetime_wtih_tz.get_current_local_date)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': "Student's Attendance Record",
                'verbose_name_plural': "Student's Attendance Records",
                'db_table': 'student_attendance',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['id', 'timestamp'], name='student_att_id_f6c46c_idx')],
            },
        ),
    ]
