# Generated by Django 5.2.3 on 2025-07-21 18:47

import utils.datetime_wtih_tz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(blank=True, default=utils.datetime_wtih_tz.get_current_local_datetime, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='timestamp',
            field=models.DateTimeField(default=utils.datetime_wtih_tz.get_current_local_datetime),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=utils.datetime_wtih_tz.get_current_local_datetime, null=True),
        ),
    ]
