# Generated by Django 5.2.3 on 2025-07-21 18:48

import utils.datetime_wtih_tz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=utils.datetime_wtih_tz.get_current_local_datetime, null=True),
        ),
    ]
