# Generated by Django 5.2.3 on 2025-07-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
